- app/src/main/AndroidManifest.xml
- app/src/main/java/ee/ria/DigiDoc/activity/OpenExternalFileActivity.java
> Adjust intent filter to avoid unnecessary mime registrations

- app/src/main/java/ee/ria/DigiDoc/fragment/ContainerDetailsFragment.java
- app/src/main/res/layout/fragment_container_details.xml
It just takes up space on the screen and does not present us with much useful information.
Besides at the moment it does not give the file location but just the name
> Don't show the file location in the container view

- app/src/main/java/ee/ria/DigiDoc/container/ContainerBuilder.java
> Rename between different mount points fails

- app/src/main/java/ee/ria/DigiDoc/adapter/SignatureAdapter.java
- app/src/main/java/ee/ria/DigiDoc/container/SignatureFacade.java
> Service does not return certificate

- app/src/main/AndroidManifest.xml
- app/src/main/java/ee/ria/DigiDoc/activity/PinUtilitiesActivity.java
- app/src/main/java/ee/ria/DigiDoc/activity/PukChangeActivity.java
- app/src/main/res/layout/puk_change.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Fix PUK back button and cleanup

- app/src/main/java/ee/ria/DigiDoc/container/DataFileFacade.java
- app/src/main/java/ee/ria/DigiDoc/fragment/ContainerDataFilesFragment.java
> Not all containers are zip-s, use libdigidocpp functions to extract datafiles

- app/src/main/res/layout/about.xml
- app/src/main/res/xml/pref_signing.xml
> About info

- app/src/main/java/ee/ria/DigiDoc/activity/OpenExternalFileActivity.java
- app/src/main/java/ee/ria/DigiDoc/adapter/DataFilesAdapter.java
- app/src/main/java/ee/ria/DigiDoc/adapter/SignatureAdapter.java
- app/src/main/java/ee/ria/DigiDoc/container/ContainerFacade.java
- app/src/main/java/ee/ria/DigiDoc/fragment/ContainerDetailsFragment.java
> Disable DDoc modification actions

- app/src/main/AndroidManifest.xml
> Open file from Goole Drive

- app/src/main/java/ee/ria/DigiDoc/activity/PinChangeActivity.java
> Don’t fall through

- app/src/main/java/ee/ria/DigiDoc/adapter/SignatureAdapter.java
- app/src/main/java/ee/ria/DigiDoc/certificate/X509Cert.java
- app/src/main/java/ee/ria/DigiDoc/container/ContainerFacade.java
- app/src/main/java/ee/ria/DigiDoc/container/SignatureFacade.java
- app/src/main/java/ee/ria/DigiDoc/fragment/ContainerDetailsFragment.java
> Disable double M-ID signing

- app/src/main/res/layout/about.xml
- app/src/main/res/xml/pref_signing.xml
> Use submenu for About info

- androidmobileid/src/main/java/ee/ria/mopp/androidmobileid/dto/response/ServiceFault.java
- androidmobileid/src/main/java/ee/ria/mopp/androidmobileid/service/MobileSignService.java
- app/src/main/java/ee/ria/DigiDoc/fragment/ContainerDetailsFragment.java
- app/src/main/java/ee/ria/DigiDoc/mid/MobileSignFaultMessageSource.java
> Cancel M-ID signing after minute

- app/src/main/java/ee/ria/DigiDoc/activity/PinChangeActivity.java
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Show message on failed PIN verification attempt

- app/src/main/java/ee/ria/DigiDoc/fragment/BrowseContainersListFragment.java
- app/src/main/res/layout/content_browse_containers.xml
> Don’t set focus to SearchView default

- app/src/main/java/ee/ria/DigiDoc/container/SignatureFacade.java
> Fix DDoc crash

- app/src/main/java/ee/ria/DigiDoc/activity/OpenExternalFileActivity.java
> Don’t assume that pdf is container

- app/src/main/java/ee/ria/DigiDoc/activity/PinUtilitiesActivity.java
- app/src/main/res/layout/activity_pin_utilities.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Show warning when card is not inserted

- app/src/main/AndroidManifest.xml
> Check that input has filename "*.*"

- app/src/main/AndroidManifest.xml
Reverts open-eid/MOPP-Android#35
As it made some app's loose the ability to share a doc to RIA DigiDoc
> Revert "Check that input has filename "*.*""

- app/build.gradle
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- build.gradle
> Allow adding multiple signatures with the same personal code

- androidmobileid/src/main/java/ee/ria/mopp/androidmobileid/dto/response/GetMobileCreateSignatureStatusResponse.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/add/SignatureAddDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/add/SignatureAddView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/ViewSavedState.java
- app/src/main/java/ee/ria/DigiDoc/mid/MobileSignStatusMessageSource.java
- app/src/main/res/layout/signature_update.xml
* 'Got signature' status not shown in the app
* 'Signing request sent' status not shown if first request was cancelled when pending
* Signing instructions not shown in the container
* Changes to 'Phone number' and 'Personal code' in system dialog saved on cancel
> Mobile ID bugfixes

- app/src/main/java/ee/ria/DigiDoc/android/signature/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Action.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Result.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateViewModel.java
Also show signing dialog right after creating matrjoska
> Show container validation screen after signing new container

- app/src/main/java/ee/ria/DigiDoc/android/crypto/CryptoHomeView.java
- app/src/main/java/ee/ria/DigiDoc/android/eid/EIDHomeView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/about/AboutScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/main/help/HelpScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/Action.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeToolbar.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeViewModel.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/Result.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/ViewState.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/home/SignatureHomeView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/list/SignatureListScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/TintUtils.java
- app/src/main/res/layout/main_home_menu.xml
- app/src/main/res/layout/signature_update_list_item_document.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings_2.xml
- app/src/main/res/values/styles.xml
Also removed document size and icon from signed container view
> Menu screen unification

- app/src/main/java/ee/ria/DigiDoc/android/utils/Formatter.java
Use activity context instead of application context for strings and date formats
> Fixed translation issues in Formatter

- mobile-id-lib/src/main/java/ee/ria/DigiDoc/mobileid/soap/ServiceGenerator.java
> Certificate pinning

- app/src/main/AndroidManifest.xml
- mobile-id-lib/src/main/java/ee/ria/DigiDoc/mobileid/soap/ServiceGenerator.java
> Mime type filter

- app/src/main/AndroidManifest.xml
- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/NameUpdateDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/NameUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateSignatureAddView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/mobileid/MobileIdView.java
- app/src/main/res/layout/signature_update_mobile_id.xml
- app/src/main/res/xml/main_settings.xml
- build.gradle
- gradle.properties
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignLib.java
* MOPPAND-89 - As a user I want to be able to send any file to MOPP2 application
* MOPPAND-128 - [Improvement] Personal code field has no max character count
* MOPPAND-129 - Mobile ID phone number field allows special characters
* MOPPAND-325 - Possible to change the container extension (corrupts the container)
* MOPPAND-327 - Possible to save container with just the extension as the name
* MOPPAND-423 - As a user I want to know which phone number format is required for mID
* MOPPAND-514 - User-Agent headeri sisu keskhalduse konfi päringul vajab mõistlikku sisu
* MOPPAND-526 - Update target API to 29
* MOPPAND-527 - Uuendada appi versiooni
> Android 2.3.1 (1)

- app/src/main/java/ee/ria/DigiDoc/android/Application.java
- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/util/FileUtils.java
* MOPPAND-578 - Jenkinsi pipeline uuendus vaikekonfiguratsiooni laadimiseks
> Android 2.3.1 (2)

- app/src/main/res/layout/signature_update_list_item_name.xml
- app/src/main/res/layout/signature_update_list_item_signature.xml
- app/src/main/res/layout/signature_update_list_item_subhead.xml
MOPPAND-193, MOPPAND-190, MOPPAND-191
> Bold container signature names and compact styles

- crypto-lib/src/main/java/ee/ria/DigiDoc/crypto/RecipientRepository.java
> LDAP search fixes

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
> File type opening changes

- app/src/main/AndroidManifest.xml
- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
> Fix rotating screen resetting app to home screen

- app/proguard-rules.pro
> Encrypting multiple files fix

- gradle.properties
> Update version to 2.4.0

- build.gradle
> Minimum requirement Android 6 (SDK 23)

- app/src/main/res/layout/widget_icon_layout.xml
- app/src/main/res/xml/main_settings.xml
> Edit icons to settings view

- app/src/main/java/ee/ria/DigiDoc/android/Application.java
> Fixed interval configuration refresh

- common-lib/src/main/java/ee/ria/DigiDoc/common/Certificate.java
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignedContainer.java
> Show friendly name on Signature title

- common-lib/src/main/java/ee/ria/DigiDoc/common/ContainerWrapper.java
- mobile-id-lib/src/main/java/ee/ria/DigiDoc/mobileid/service/MobileSignService.java
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/service/SmartSignService.java
MOPPAND-664\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Remove unnecessary validation right after signature finalization

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
MOPPAND-609\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Display alert dialog on startup when device is rooted

- app/src/main/java/ee/ria/DigiDoc/android/Application.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/TSLUtil.java
- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/util/FileUtils.java
MOPPAND-681\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Copy tsl files from assets to cache only when non-existent or outdated

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- gradle.properties
MOPPAND-599\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Open cdoc files in crypto screen

- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/TSLException.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/TSLUtil.java
MOPPAND-630\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> TSL version in diagnostics view

- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsFragment.java
- app/src/main/res/xml/main_settings.xml
MOPPAND-665\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Remove phone number (with country code) and personal code from settings

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Result.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/ViewState.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/container/NameUpdateDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/container/NameUpdateView.java
- app/src/main/res/layout/crypto_create_list_item_name.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
MOPPAND-574\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Introduce the ability to change the name of unfinalized crypto container

- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
- app/src/main/res/layout/main_diagnostics.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
MOPPAND-671\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Show cached TSL files and their versions in diagnostics

- app/src/main/java/ee/ria/DigiDoc/android/Constants.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Action.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Result.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/IntentUtils.java
- app/src/main/res/drawable/ic_icon_save.xml
- app/src/main/res/layout/crypto_create_list_item_data_file.xml
- app/src/main/res/layout/signature_update_list_item_document.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
MOPPAND-179\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Added support for saving files from container

- lgtm.yml
MOPPAND-700\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Trying to fix lgtm

- buildSrc/src/main/java/ee/ria/DigiDoc/android/UpdateLibdigidocppTask.java
- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/task/FetchAndPackageDefaultConfigurationTask.java
MOPPAND-700\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Fix some alerts reported by LGTM

- app/src/main/java/ee/ria/DigiDoc/android/model/mobileid/MobileIdStatusMessages.java
- app/src/main/java/ee/ria/DigiDoc/android/model/smartid/SmartIdStatusMessages.java
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
- common-lib/src/main/java/ee/ria/DigiDoc/common/UUIDUtil.java
- mobile-id-lib/src/main/java/ee/ria/DigiDoc/mobileid/dto/response/MobileCreateSignatureSessionStatusResponse.java
- mobile-id-lib/src/main/java/ee/ria/DigiDoc/mobileid/service/MobileSignService.java
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/dto/response/SessionStatusResponse.java
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/service/SmartSignService.java
MOPPAND-661\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Show specific message when authorization for signing with Mobile-ID fails

- app/src/main/java/ee/ria/DigiDoc/android/main/sharing/SharingScreenView.java
MOPPAND-694\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Fix potential nullpointer

- configuration-lib/src/main/java/androidx/core/app/PatchedJobIntentService.java
- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/ConfigurationManagerService.java
MOPPAND-697\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Potential JobIntentService bug fix

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/smartid/SmartIdOnSubscribe.java
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/service/SmartSignService.java
MOPPAND-660\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Improve smart-ID broadcasting

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
MOPPAND-142\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Permit signing ddoc and asics containers

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/model/mobileid/MobileIdStatusMessages.java
- app/src/main/java/ee/ria/DigiDoc/android/model/smartid/SmartIdStatusMessages.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/data/source/FileSystemSignatureContainerDataSource.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateErrorDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
- crypto-lib/src/main/java/ee/ria/DigiDoc/crypto/NoInternetConnectionException.java
- crypto-lib/src/main/java/ee/ria/DigiDoc/crypto/RecipientRepository.java
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignedContainer.java
MOPPAND-617\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Improve error messages when dealing with missing internet connection

- buildSrc/src/main/java/ee/ria/DigiDoc/android/UpdateLibdigidocppTask.java
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignLib.java
MOPPAND-700\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Fix errors reported by LGTM

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateProgressBar.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/res/layout/signature_update.xml
- app/src/main/res/values/ids.xml
MOPPAND-642\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Modified verification code view for Smart-ID and Mobile-ID

- app/src/main/AndroidManifest.xml
- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
MOPPAND-683\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Allow multiple incoming files from other apps + also accept audio files

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsDataStore.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/widget/NotificationDialog.java
- app/src/main/res/layout/crash_report_dialog.xml
- app/src/main/res/layout/success_notification_dialog.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
MOPPAND-622\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Show notification after successful sign/encrypt

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/list/SignatureListScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateSignatureAddView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/widget/ConfirmationDialog.java
- app/src/main/res/layout/crypto_create_screen.xml
- app/src/main/res/layout/signature_update_signature_add.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
> Accessibility elements feedback improved

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/DecryptDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/eid/CertificateDataView.java
- app/src/main/java/ee/ria/DigiDoc/android/eid/EIDDataView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/idcard/IdCardView.java
- app/src/main/res/layout/eid_home_certificate_data.xml
- app/src/main/res/layout/eid_home_data.xml
- app/src/main/res/layout/signature_update_id_card.xml
> Accessibility input field error handling

- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeView.java
- app/src/main/res/menu/main_home_navigation.xml
MOPPAND-551\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> My eID navigation item accessibility talkback improvements

- app/src/main/java/ee/ria/DigiDoc/android/crypto/home/CryptoHomeView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/home/SignatureHomeView.java
> Improved focus order

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/DecryptDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/TsaUrlPreferenceDialogFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/UUIDPreferenceDialogFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateSignatureAddDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/SecureUtil.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/container/NameUpdateDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/widget/ConfirmationDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/widget/ErrorDialog.java
MOPPAND-610\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Disable screen capture/recording in case of non DEBUG build

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/container/NameUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/display/DisplayUtil.java
- app/src/main/res/layout/crypto_create_list_item_data_file.xml
- app/src/main/res/layout/crypto_recipients_screen.xml
- app/src/main/res/layout/eid_home_code_update.xml
- app/src/main/res/layout/signature_update_id_card.xml
- app/src/main/res/layout/signature_update_mobile_id.xml
- app/src/main/res/layout/signature_update_smart_id.xml
- app/src/main/res/xml/main_settings.xml
> Accessibility touch area size improvements

- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
- mobile-id-lib/src/main/java/ee/ria/DigiDoc/mobileid/service/MobileSignService.java
MOPPAND-696\n\nSigned-off-by: Andres Voll <andres.voll@nortal.com>\n
> Improve mobile-ID sign error handling

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateSignatureAddView.java
- app/src/main/res/layout/signature_update_signature_add.xml
- app/src/main/res/menu/main_home_navigation.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Accessibility Navigation tab more precise identification

- app/src/main/java/ee/ria/DigiDoc/android/model/mobileid/MobileIdStatusMessages.java
- app/src/main/java/ee/ria/DigiDoc/android/model/smartid/SmartIdStatusMessages.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/res/layout/signature_update.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
- mobile-id-lib/src/main/java/ee/ria/DigiDoc/mobileid/dto/response/MobileCreateSignatureSessionStatusResponse.java
- mobile-id-lib/src/main/java/ee/ria/DigiDoc/mobileid/service/MobileSignService.java
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/dto/response/SessionStatusResponse.java
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/service/SmartSignService.java
> Added HTTP code 429 support for Mobile-ID and Smart-ID

- build.gradle
> Minimum requirement Android 8

- configuration-lib/src/androidTest/assets/config/configuration.properties
- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/ConfigurationManager.java
- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/task/FetchAndPackageDefaultConfigurationTask.java
- configuration-lib/src/main/resources/default-configuration.properties
- configuration-lib/src/test/resources/configuration.properties
> Central Configuration update interval changes

- app/src/main/java/ee/ria/DigiDoc/android/model/smartid/SmartIdStatusMessages.java
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/dto/response/SessionStatusResponse.java
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/service/SmartSignService.java
> Account not found and timeout same error message

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/data/source/FileSystemSignatureContainerDataSource.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/IntentUtils.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/files/FileSystem.java
- common-lib/src/main/java/ee/ria/DigiDoc/common/FileUtil.java
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignedContainer.java
> Restrict characters

- app/build.gradle
- app/src/main/java/ee/ria/DigiDoc/android/Application.java
- app/src/main/java/ee/ria/DigiDoc/android/eid/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/main/about/AboutAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsDataStore.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/Formatter.java
- app/src/main/res/values/donottranslate.xml
- build.gradle
- common-lib/build.gradle
- common-lib/src/main/java/ee/ria/DigiDoc/common/Certificate.java
- crypto-lib/build.gradle
- id-card-lib/build.gradle
- id-card-lib/src/main/java/ee/ria/DigiDoc/idcard/EstEIDToken.java
- id-card-lib/src/main/java/ee/ria/DigiDoc/idcard/ID1PersonalDataParser.java
- id-card-lib/src/main/java/ee/ria/DigiDoc/idcard/PersonalData.java
- sign-lib/build.gradle
- sign-lib/src/androidTest/java/ee/ria/DigiDoc/sign/SignedContainerSubject.java
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/Signature.java
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignedContainer.java
> DDOC status changes

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignatureStatus.java
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignedContainer.java
> Removed test signature type

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
> Remove warning for invalid signatures

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateErrorDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/ToastUtil.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/files/EmptyFileException.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/files/FileSystem.java
- app/src/main/res/layout/signature_update_list_item_empty.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignedContainer.java
> Forbid adding and signing 0 byte files

- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignLib.java
> Libdigidocpp logs location

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- app/src/main/java/ee/ria/DigiDoc/android/main/sharing/SharingScreenView.java
> Fix choosing files crash

- app/src/main/java/ee/ria/DigiDoc/android/signature/data/source/FileSystemSignatureContainerDataSource.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/files/FileSystem.java
- common-lib/src/main/java/ee/ria/DigiDoc/common/FileUtil.java
> Sanitize text

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/data/source/FileSystemSignatureContainerDataSource.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/list/SignatureListScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/IntentUtils.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/SivaUtil.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/files/FileStream.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/files/FileSystem.java
- common-lib/build.gradle
- common-lib/src/main/java/ee/ria/DigiDoc/common/FileUtil.java
- configuration-lib/build.gradle
- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/util/FileUtils.java
- mobile-id-lib/src/main/java/ee/ria/DigiDoc/mobileid/service/MobileSignService.java
- sign-lib/build.gradle
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignedContainer.java
> Code improvements

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/SivaUtil.java
> Fixed SiVa warning showing in container

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
> SiVa warning improvements

- app/src/main/java/ee/ria/DigiDoc/android/signature/list/Result.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/files/FileSystem.java
- crypto-lib/src/main/java/ee/ria/DigiDoc/crypto/CryptoContainer.java
> Show only containers in recent documents

- gradle.properties
> Update version to 2.4.5

- app/src/main/java/ee/ria/DigiDoc/android/utils/container/NameUpdateDialog.java
> Fix container name change textfield design

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/mobileid/MobileCreateSignatureRequestHelper.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/smartid/SmartCreateSignatureRequestHelper.java
- app/src/main/res/values-ru/strings.xml
- build.gradle
- common-lib/build.gradle
- common-lib/src/main/java/ee/ria/DigiDoc/common/MessageUtil.java
- mobile-id-lib/build.gradle
- mobile-id-lib/src/main/java/ee/ria/DigiDoc/mobileid/rest/MIDRestServiceClient.java
- mobile-id-lib/src/main/java/ee/ria/DigiDoc/mobileid/rest/ServiceGenerator.java
- mobile-id-lib/src/main/java/ee/ria/DigiDoc/mobileid/service/MobileSignService.java
- smart-id-lib/build.gradle
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/rest/SIDRestServiceClient.java
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/rest/ServiceGenerator.java
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/service/SmartSignService.java
> Mobile-ID and Smart-ID russian text support

- app/src/main/java/ee/ria/DigiDoc/android/eid/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/IntentUtils.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/LocaleService.java
> Open links based on application language

- app/src/main/java/ee/ria/DigiDoc/android/Application.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsViewModel.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/Result.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/ViewState.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/source/DiagnosticsDataSource.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/source/FileSystemDiagnosticsDataSource.java
- app/src/main/res/layout/main_diagnostics.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
> Save diagnostics

- app/src/main/java/ee/ria/DigiDoc/android/signature/data/source/FileSystemSignatureContainerDataSource.java
> Fixed container file naming

- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
- app/src/main/res/layout/main_diagnostics.xml
- app/src/main/res/values/ids.xml
- configuration-lib/src/androidTest/java/ee/ria/DigiDoc/configuration/ConfigurationManagerTest.java
- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/ConfigurationManager.java
- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/ConfigurationProvider.java
> Remove MID-SIGN-URL configuration field

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
> No signature removal icon for unsupported containers

- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
> Fixed multiple data entries on configuration refresh

- build.gradle
- lgtm.yml
> Update Target API to 31

- app/src/main/AndroidManifest.xml
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateSignatureAddDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateSignatureAddView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/display/DisplayUtil.java
- app/src/main/res/layout/signature_update_mobile_id.xml
- app/src/main/res/layout/signature_update_signature_add.xml
> Fix text field hidden behind keyboard in signing view

- app/src/main/AndroidManifest.xml
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/TsaUrlPreferenceDialogFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/UUIDPreferenceDialogFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateErrorDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateSignatureAddDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateSignatureAddView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/display/DisplayUtil.java
- app/src/main/res/layout/signature_update_signature_add.xml
> Settings fields horizontal view fixes 

- app/src/main/java/ee/ria/DigiDoc/android/model/smartid/SmartIdStatusMessages.java
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/dto/response/SessionStatusResponse.java
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/service/SmartSignService.java
> Timeout message fixes

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/res/layout/signature_update_list_item_signature.xml
> Fixed name clipping in signature view

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Group signature view tabs

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateSignatureAddDialog.java
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Accessibility process feedback improvements

- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
- app/src/main/res/layout/main_diagnostics.xml
- app/src/main/res/values/donottranslate.xml
> Fixed Diagnostics view with large fonts

- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsDataStore.java
> Show modified TSA url in Diagnostics view

- build.gradle
> Updated LDAP SDK version to 6.0.4

- app/src/main/java/ee/ria/DigiDoc/android/main/about/AboutAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/TsaUrlPreference.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/UUIDPreference.java
- app/src/main/res/layout/main_home_menu.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/xml/main_settings.xml
- common-lib/src/main/java/ee/ria/DigiDoc/common/TextUtil.java
> Settings view accessibility improvements

- app/src/main/AndroidManifest.xml
- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/LocaleService.java
> Restore app state on phone configuration changes

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/main/about/AboutAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateSignatureAddView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/TextUtil.java
- app/src/main/res/layout/crypto_create_decrypt_dialog.xml
- app/src/main/res/layout/crypto_list_item_recipient.xml
- app/src/main/res/layout/crypto_recipients_screen.xml
- app/src/main/res/layout/main_home_menu.xml
- app/src/main/res/layout/signature_list_item.xml
- app/src/main/res/layout/signature_update_list_item_signature.xml
- app/src/main/res/layout/signature_update_mobile_id.xml
- app/src/main/res/layout/signature_update_signature_add.xml
- app/src/main/res/layout/signature_update_smart_id.xml
- app/src/main/res/layout/success_notification_dialog.xml
- common-lib/src/main/java/ee/ria/DigiDoc/common/TextUtil.java
> Maximum text and display size design improvements

- .github/workflows/build.yml
> Github Actions support

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
> Updated Android Gradle version to 7.1.2

- build.gradle
> Updated AndroidX version to 1.3.0

- build.gradle
> Updated Android Material version to 1.5.0

- build.gradle
> Updated AndroidX Constraint Layout version to 2.1.3

- build.gradle
> Updated Guava version to 31.1

- build.gradle
> Updated Okio version to 3.0.0

- build.gradle
> Updated SLF4J version to 1.7.36

- build.gradle
> Updated bcpkix-jdk15on version to 1.70

- build.gradle
> Updated Dagger version to 2.41

- build.gradle
> Updated RxJava version to 3.1.4

- build.gradle
> Updated AutoValue version to 1.9

- build.gradle
> Updated Firebase Android BoM version to 29.3.0

- build.gradle
> Updated OkHttp to version 4.9.3

- build.gradle
> Updated Mockito Core to version 4.4.0

- build.gradle
> Updated AndroidX Test Orchestrator to version 1.4.1

- build.gradle
> Updated AndroidX Local Broadcast Manager to version 1.1.0

- build.gradle
> Updated Firebase Crashlytics Gradle version to 2.8.1

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/detail/CertificateDetailView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/detail/SignatureDetailView.java
- common-lib/src/main/java/ee/ria/DigiDoc/common/FileUtil.java
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignedContainer.java
> Coverity fixes

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
> Fixed signature removing

- app/src/main/AndroidManifest.xml
> Fixed keyboard not closing

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureAddSource.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/mobileid/MobileCreateSignatureRequestHelper.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/mobileid/MobileIdOnSubscribe.java
> Fixed Mobile-ID signing error

- gradle.properties
- mobile-id-lib/src/main/java/ee/ria/DigiDoc/mobileid/rest/ServiceGenerator.java
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/rest/ServiceGenerator.java
> Increased timeouts

- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuView.java
- gradle.properties
> Fixed accessibility crash on startup

- app/src/main/res/layout/main_about_header.xml
- app/src/main/res/layout/main_home_toolbar.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Accessible DigiDoc and EL logos

- app/src/main/res/drawable/border_background.xml
- app/src/main/res/values/themes.xml
> Added border to textviews

- app/src/main/java/ee/ria/DigiDoc/android/main/about/AboutAdapter.java
> Added link word to Info urls

- gradle.properties
> Updated version to 2.5.0

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/mobileid/MobileIdView.java
- app/src/main/res/layout/signature_update_mobile_id.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/strings.xml
> Added errors to Mobile-ID fields

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/smartid/SmartIdView.java
- app/src/main/res/layout/signature_update_smart_id.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Added errors to Smart-ID field

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/DecryptDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/eid/CodeUpdateAction.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/idcard/IdCardView.java
- app/src/main/res/layout/crypto_create_decrypt_dialog.xml
- app/src/main/res/layout/signature_update_id_card.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
- common-lib/src/main/java/ee/ria/DigiDoc/common/PinConstants.java
> Added errors to ID-card fields

- app/src/main/java/ee/ria/DigiDoc/android/accessibility/AccessibilityUtils.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/TextUtil.java
- app/src/main/res/layout/main_home_menu.xml
> Fixed English button size

- app/src/main/java/ee/ria/DigiDoc/android/accessibility/AccessibilityUtils.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/smartid/SmartIdOnSubscribe.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/Formatter.java
- build.gradle
> Removed Android 8 and 8.1 support

- app/src/main/res/layout/crypto_home.xml
- app/src/main/res/layout/signature_home.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Updated translations

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateProgressBar.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/res/layout/signature_update.xml
- app/src/main/res/values/ids.xml
> Fixed showing Mobile-ID signing progress

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
> Fixed adding multiple of the same recipients

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
> Fixed not adding other files when a file already exists

- app/src/main/java/ee/ria/DigiDoc/android/Constants.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/mobileid/MobileIdView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/smartid/SmartIdView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/validator/PersonalCodeValidator.java
> Check personal code

- app/src/main/java/ee/ria/DigiDoc/android/eid/Processor.java
- id-card-lib/src/main/java/ee/ria/DigiDoc/idcard/ID1PersonalDataParser.java
> ID-card validation improvements

- app/src/main/java/ee/ria/DigiDoc/android/accessibility/AccessibilityUtils.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/mobileid/MobileIdView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/smartid/SmartIdView.java
- app/src/main/res/layout/signature_update_mobile_id.xml
- app/src/main/res/layout/signature_update_smart_id.xml
> Accessibility signing fields labels on textfields

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/mobileid/MobileIdView.java
- app/src/main/res/drawable/bottom_border_background.xml
- app/src/main/res/layout/signature_update_mobile_id.xml
> Mobile-ID border improvements

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/mobileid/MobileIdView.java
- app/src/main/res/drawable/bottom_border_background.xml
- app/src/main/res/layout/signature_update_mobile_id.xml
- app/src/main/res/layout/signature_update_smart_id.xml
> Smart-ID border improvements

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
> Crypto recipient search improvements

- app/src/main/java/ee/ria/DigiDoc/android/eid/CodeUpdateView.java
- app/src/main/res/layout/eid_home_code_update.xml
- app/src/main/res/values/ids.xml
> Added errors to My eID PIN code fields

- app/src/main/java/ee/ria/DigiDoc/android/accessibility/AccessibilityUtils.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/mobileid/MobileIdView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/smartid/SmartIdView.java
- app/src/main/res/layout/signature_update_mobile_id.xml
- app/src/main/res/layout/signature_update_smart_id.xml
- app/src/main/res/values/ids.xml
> Border fixes

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/ToastUtil.java
- common-lib/src/main/java/ee/ria/DigiDoc/common/ActivityUtil.java
> Fixed crashes

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/DecryptDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsDataStore.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/TsaUrlPreferenceDialogFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/UUIDPreferenceDialogFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateSignatureAddDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/SecureUtil.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/container/NameUpdateDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/widget/ConfirmationDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/widget/ErrorDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/widget/NotificationDialog.java
- app/src/main/res/layout/main_settings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
> Allow screenshots in Settings

- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/Processor.java
- app/src/main/res/layout/crypto_list_item_subhead.xml
- app/src/main/res/layout/signature_update_list_item_subhead.xml
- app/src/main/res/menu/main_home_navigation.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Added heading trait to headings

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/files/FileAlreadyExistsException.java
- common-lib/src/main/java/ee/ria/DigiDoc/common/FileUtil.java
> Fixed adding duplicate files

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Result.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/Immutables.java
- app/src/main/res/layout/crypto_list_item_add_all_button.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
> Add all recipients

- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/res/layout/crypto_create_screen.xml
- app/src/main/res/layout/main_home_menu.xml
- app/src/main/res/layout/signature_update.xml
> Buttons design improvements

- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/util/UserAgentUtil.java
> Updated user-agent

- app/src/main/res/layout/crypto_create_screen.xml
> Decrypt button design fix

- build.gradle
> Updated Commons Text to 1.10.0

- app/build.gradle
- app/src/main/AndroidManifest.xml
- app/src/main/res/values-et/strings.xml
- build.gradle
- common-lib/build.gradle
- common-lib/src/main/AndroidManifest.xml
- configuration-lib/build.gradle
- configuration-lib/src/androidTest/AndroidManifest.xml
- configuration-lib/src/main/AndroidManifest.xml
- crypto-lib/build.gradle
- crypto-lib/src/main/AndroidManifest.xml
- gradle/wrapper/gradle-wrapper.properties
- id-card-lib/build.gradle
- id-card-lib/src/main/AndroidManifest.xml
- mobile-id-lib/build.gradle
- mobile-id-lib/src/main/AndroidManifest.xml
- sign-lib/build.gradle
- sign-lib/src/main/AndroidManifest.xml
- smart-card-reader-lib/build.gradle
- smart-card-reader-lib/src/main/AndroidManifest.xml
- smart-id-lib/build.gradle
- smart-id-lib/src/main/AndroidManifest.xml
> Updated Android Gradle version to 7.3.1

- build.gradle
> Updated AndroidX Annotation version to 1.5.0

- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuView.java
> Fixed voice locale

- app/src/main/AndroidManifest.xml
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/IntentUtils.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/validator/PersonalCodeValidator.java
- common-lib/src/main/java/ee/ria/DigiDoc/common/DateOfBirthUtil.java
- id-card-lib/build.gradle
- id-card-lib/src/main/java/ee/ria/DigiDoc/idcard/ID1PersonalDataParser.java
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/Signature.java
> App stability improvements

- build.gradle
> Updated Crashlytics Gradle plugin to 2.9.2

- build.gradle
> Updated target API level to 33

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/list/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/list/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/list/SignatureListScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/SivaUtil.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/ToastUtil.java
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignedContainer.java
> Improved PDF files opening

- build.gradle
> Updated Android Material to version 1.7.0

- build.gradle
> Updated Okio version to 3.3.0

- build.gradle
> Updated ConstraintLayout version to 2.1.4

- build.gradle
> Updated Dagger to version 2.44.2

- build.gradle
> Updated RxJava to 3.1.5

- build.gradle
> Updated AutoValue version to 1.10.1

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- build.gradle
> Updated Firebase BOM to version 31.1.1

- build.gradle
> Updated LDAP SDK to version 6.0.7

- build.gradle
> Updated OkHTTP to version 4.10.0

- build.gradle
> Updated Mockito Core version to 4.11.0

- build.gradle
> Updated AndroidX Test Orchestrator version to 1.4.2

- build.gradle
> Downgraded Gradle plugin to fix building

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/smartid/SmartIdOnSubscribe.java
> Added No Internet Connection message to Smart-ID

- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Smart-ID error message fixes

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
- app/src/main/res/layout/crypto_recipients_screen.xml
> Search button improvements

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
> Improved crypto recipient accessibility

- app/src/main/res/layout/signature_update.xml
> Cancel button improvements

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
> Fixed cancelling ID-card signing

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/list/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
> Fixed ASIC-S container opening

- app/src/main/java/ee/ria/DigiDoc/android/utils/IntentUtils.java
> Share menu improvements

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
> Fixed opening external files

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
> Fixed opening DDOC inside ASIC-S container

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/IntentUtils.java
> Remove app from "Open with" menu

- app/src/main/AndroidManifest.xml
- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/smartid/SmartIdOnSubscribe.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/navigator/Navigator.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/navigator/RequestPermissionsResult.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/navigator/conductor/ConductorNavigator.java
> Android 13 notifications support

- app/src/main/java/ee/ria/DigiDoc/android/Constants.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/IntentUtils.java
- app/src/main/res/xml/file_provider_paths.xml
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/service/SmartSignService.java
> Smart-ID and file saving fixes

- gradle.properties
> Updated version to 2.6.0

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
> Hide crypto confirm button when no addressees

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
> Remove search results when searchfield is empty

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/validator/PersonalCodeValidator.java
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
- crypto-lib/src/main/java/ee/ria/DigiDoc/crypto/PersonalCodeException.java
> Improved crypto view personal code handling

- .github/workflows/build.yml
- buildSrc/src/main/java/ee/ria/DigiDoc/android/UpdateLibdigidocppTask.java
> Update libdigidocpp in Github Actions

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
> Font size fixes

- app/src/main/res/layout/signature_update_list_item_empty.xml
- app/src/main/res/layout/signature_update_list_item_status.xml
> Added spacing to container notifications

- app/src/main/java/ee/ria/DigiDoc/android/utils/SivaUtil.java
> No SiVa confirmation dialog with multiple files

- app/src/main/res/layout/signature_update_list_item_signature.xml
- app/src/main/res/layout/signature_update_list_item_timestamp.xml
- app/src/main/res/values/colors.xml
> Updated notification messages background color

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
- app/src/main/res/values-et/strings.xml
> Changed header for pre-encrypted files

- app/build.gradle
- build.gradle
- common-lib/build.gradle
- configuration-lib/build.gradle
- crypto-lib/build.gradle
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
- id-card-lib/build.gradle
- mobile-id-lib/build.gradle
- sign-lib/build.gradle
- smart-card-reader-lib/build.gradle
- smart-id-lib/build.gradle
> Updated Android Gradle version to 8.1.0

- app/src/main/java/ee/ria/DigiDoc/android/eid/CodeUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/eid/Processor.java
> ID-card PIN changing fixes

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/container/NameUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/files/FileStream.java
- common-lib/src/main/java/ee/ria/DigiDoc/common/FileUtil.java
> Default container name when file name is empty

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateSignatureAddDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateSignatureAddView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/res/layout/crypto_create_decrypt_dialog.xml
- app/src/main/res/layout/signature_update_id_card.xml
- app/src/main/res/layout/signature_update_mobile_id.xml
- app/src/main/res/layout/signature_update_smart_id.xml
- app/src/main/res/values/ids.xml
> Horizontal view improvements

- app/src/main/java/ee/ria/DigiDoc/android/Application.java
- app/src/main/java/ee/ria/DigiDoc/android/Constants.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsDataStore.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/TsaUrlPreference.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/TsaUrlPreferenceDialogFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/create/Action.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/create/ChooseFileScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/create/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/create/Result.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/create/TSACertificateAddViewModel.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/create/ViewState.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/create/Action.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Action.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/IntentUtils.java
- app/src/main/res/layout/main_settings.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/donottranslate.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
- common-lib/src/main/java/ee/ria/DigiDoc/common/CommonConstants.java
- common-lib/src/main/java/ee/ria/DigiDoc/common/FileUtil.java
- common-lib/src/main/res/values/donottranslate.xml
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignLib.java
> Added TSA cert pinning

- app/src/main/java/ee/ria/DigiDoc/android/eid/EIDHomeView.java
- app/src/main/res/layout/eid_home.xml
- app/src/main/res/values/ids.xml
> Added spinner to My eID loading view

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- app/src/main/java/ee/ria/DigiDoc/android/main/sharing/SharingScreenView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/create/Processor.java
> Improved adding file support from Open From menu

- app/src/main/java/ee/ria/DigiDoc/android/accessibility/AccessibilityUtils.java
- app/src/main/java/ee/ria/DigiDoc/android/eid/EIDDataView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/detail/SignatureDetailView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/res/layout/signature_detail_screen.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/colors.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/Signature.java
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignedContainer.java
> Added signature warnings info

- app/src/main/java/ee/ria/DigiDoc/android/main/home/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/access/SettingsAccessScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/access/SettingsAccessView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/access/SettingsFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/access/TsaUrlPreference.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/access/TsaUrlPreferenceDialogFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/access/UUIDPreference.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/access/UUIDPreferenceDialogFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/create/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/create/Result.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/util/SettingsUtil.java
- app/src/main/res/drawable/ic_icon_access_padded.xml
- app/src/main/res/layout/main_settings.xml
- app/src/main/res/layout/main_settings_access.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/xml/main_settings_access.xml
> New Settings design

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/list/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/IntentUtils.java
- app/src/main/res/layout/crypto_create_screen.xml
- app/src/main/res/values/ids.xml
> Added Sign button to crypto view

- build.gradle
> Updated Crashlytics version to 2.9.8

- build.gradle
> Updated AndroidX Annotation version to 1.6.0

- build.gradle
> Updated Android Material version to 1.9.0

- build.gradle
> Updated Okio version to 3.5.0

- build.gradle
> Updated Dagger version to 2.47

- build.gradle
> Updated LDAP SDK version to 6.0.9

- build.gradle
> Updated OkHttp version to 4.11.0

- build.gradle
> Updated AndroidX Core version to 1.10.1

- build.gradle
- smart-card-reader-lib/src/test/java/ee/ria/DigiDoc/smartcardreader/SmartCardReaderTest.java
> Updated Mockito version to 5.4.0

- buildSrc/src/main/java/ee/ria/DigiDoc/android/UpdateLibdigidocppTask.java
- gradle.properties
> Removed x86 support

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateErrorDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/TextUtil.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/widget/ErrorDialog.java
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values/themes.xml
> Fixed maximum font design

- app/src/main/res/values/colors.xml
> Color update

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/list/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateErrorDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/ToastUtil.java
- app/src/main/res/layout/signature_list_screen.xml
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignedContainer.java
> Improved messages without Internet connection

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
- app/src/main/res/layout/crypto_recipients_screen.xml
- app/src/main/res/values/ids.xml
> Fixed keyboard jumping in crypto view

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Action.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Result.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/IntentUtils.java
- app/src/main/res/drawable/ic_icon_save_container.xml
- app/src/main/res/layout/crypto_create_list_item_name.xml
- app/src/main/res/layout/main_home_menu.xml
- app/src/main/res/layout/signature_list_item.xml
- app/src/main/res/layout/signature_update_list_item_document.xml
- app/src/main/res/layout/signature_update_list_item_name.xml
- app/src/main/res/layout/signature_update_list_item_signature.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
- crypto-lib/src/main/java/ee/ria/DigiDoc/crypto/CryptoContainer.java
> Added Save button to containers

- app/src/main/java/ee/ria/DigiDoc/android/accessibility/AccessibilityUtils.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Improved Voice assistant support for crypto view

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/main/about/AboutScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/list/SignatureListScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateSignatureAddDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/mobileid/MobileIdView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/smartid/SmartIdView.java
- app/src/main/res/layout/signature_update_id_card.xml
- app/src/main/res/layout/signature_update_mobile_id.xml
- app/src/main/res/layout/signature_update_smart_id.xml
- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/verify/ConfigurationSignatureVerifier.java
> Improved large text accessibility in signing view

- app/src/main/java/ee/ria/DigiDoc/android/accessibility/AccessibilityUtils.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoRecipientsScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/mobileid/MobileIdView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/smartid/SmartIdView.java
- app/src/main/res/layout/signature_update_mobile_id.xml
- common-lib/src/main/java/ee/ria/DigiDoc/common/TextUtil.java
> Improved Voice assistant support for signing view

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/list/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
> Fix container and crypto accessibility

- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsDataStore.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/access/SettingsAccessView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/role/SettingsRoleAndAddressView.java
- app/src/main/res/layout/certificate_details_screen.xml
- app/src/main/res/layout/main_settings.xml
- app/src/main/res/layout/main_settings_access.xml
- app/src/main/res/layout/main_settings_role_and_address.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignLib.java
> Use default settings 

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/idcard/IdCardView.java
> Fix TalkBack reading name as single characters

- app/src/main/java/ee/ria/DigiDoc/android/main/accessibility/AccessibilityView.java
- app/src/main/res/layout/main_accessibility.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
MOPPAND-1138: Add more info link to Accessibility view.
Signed-off-by: Boriss Melikjan <boriss.melikjan@nortal.com>
> Add link to Accessibility text

- app/src/main/res/layout/main_settings_rights.xml
- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/verify/ConfigurationSignatureVerifier.java
> Fix reseting SiVa settings

- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/SettingsSigningView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/siva/SettingsSivaDialog.java
- app/src/main/res/layout/main_settings_signing.xml
- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/verify/ConfigurationSignatureVerifier.java
> Fix settings reseting

- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/SettingsSigningView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/siva/SettingsSivaDialog.java
- app/src/main/res/layout/main_settings.xml
- app/src/main/res/layout/main_settings_rights.xml
> Add new design for Settings view

- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/SettingsSigningView.java
- app/src/main/res/layout/certificate_details_screen.xml
- app/src/main/res/layout/main_settings_proxy_dialog_layout.xml
- app/src/main/res/layout/main_settings_rights.xml
- app/src/main/res/layout/main_settings_signing.xml
- app/src/main/res/layout/main_settings_siva_dialog_layout.xml
> Fix settings accessibility headings

- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/SettingsSigningView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/siva/SettingsSivaDialog.java
> Fix removing SiVa certificate

- .github/workflows/build.yml
> Fix Github Actions build

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/idcard/IdCardView.java
- app/src/main/res/layout/eid_home_code_update.xml
- app/src/main/res/layout/main_settings_proxy_dialog_layout.xml
- app/src/main/res/layout/signature_update_mobile_id.xml
- app/src/main/res/layout/signature_update_smart_id.xml
> Fix textfield sizes

- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/siva/SettingsSivaDialog.java
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignLib.java
> Fix SiVa and TSA url setting

- app/src/main/java/ee/ria/DigiDoc/android/crypto/home/CryptoHomeView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/home/SignatureHomeView.java
- app/src/main/res/drawable/transparent_button.xml
- app/src/main/res/layout/crypto_home.xml
- app/src/main/res/layout/main_home_menu.xml
- app/src/main/res/layout/signature_home.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/ids.xml
- app/src/main/res/values/strings.xml
> Added Recent Documents button to main screen

- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
> Removed TSL version from URL view

- app/src/main/java/ee/ria/DigiDoc/android/accessibility/AccessibilityUtils.java
- build.gradle
> Remove support for Android 9 and 10

- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/util/UserAgentUtil.java
> Fix User-Agent version

- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsView.java
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Add message when settings reset

- smart-card-reader-lib/src/main/java/ee/ria/DigiDoc/smartcardreader/SmartCardReaderOnSubscribe.java
> Fix reading ID-card

- app/src/main/res/layout/eid_home_code_update.xml
> Fix button misplacement

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- app/src/main/java/ee/ria/DigiDoc/android/Constants.java
- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeMenuView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/HomeView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/home/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/SettingsDataStore.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/rights/SettingsRightsView.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/ViewType.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/navigator/Transaction.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/navigator/conductor/ConductorNavigator.java
- app/src/main/res/layout/main_home_menu.xml
- common-lib/src/main/res/values/donottranslate.xml
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignLib.java
> Return to last screen on app restart

- app/src/main/java/ee/ria/DigiDoc/android/accessibility/AccessibilityUtils.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/SettingsFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/TsaUrlPreference.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/UUIDPreference.java
> Say correct translation for settings buttons

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/DecryptDialog.java
> Disable decrypt button when decrypting

- app/src/main/java/ee/ria/DigiDoc/android/main/about/AboutAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/model/mobileid/MobileIdStatusMessages.java
- app/src/main/java/ee/ria/DigiDoc/android/model/smartid/SmartIdStatusMessages.java
- app/src/main/res/layout/main_about_screen.xml
- app/src/main/res/layout/signature_list_screen.xml
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
- common-lib/src/main/java/ee/ria/DigiDoc/common/TextUtil.java
- common-lib/src/main/res/values-et/strings.xml
- common-lib/src/main/res/values-ru/strings.xml
- common-lib/src/main/res/values/strings.xml
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/utils/UrlMessage.java
> Replace too many requests error

- gradle.properties
> Update app version code

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- smart-card-reader-lib/src/main/java/ee/ria/DigiDoc/smartcardreader/SmartCardReaderOnSubscribe.java
> Updated Android Gradle to version 8.2.2

- build.gradle
> Update Crashlytics version to 2.9.9

- build.gradle
> Update AndroidX to version 1.7.1

- build.gradle
> Update Android Recyclerview version to 1.3.2

- build.gradle
> Updated Guava version to 33.0.0

- build.gradle
> Update Okio version to 3.8.0

- build.gradle
> Update Commons Text version to 1.11.0

- build.gradle
> Updated Dagger version to 2.51

- build.gradle
> Update RxJava version to 3.1.8

- build.gradle
> Updated AutoValue version to 1.10.4

- build.gradle
> Update Firebase version to 32.7.3

- build.gradle
> Update truth version to 1.4.2

- build.gradle
> Update OkHttp version to 4.12.0

- build.gradle
> Update Google Services version to 4.4.1

- build.gradle
> Updated Android Material to version 1.11.0

- build.gradle
> Update AndroidX Lifecycle version to 2.7.0

- build.gradle
> Updated Commons IO version to 2.15.1

- build.gradle
> Update AndroidX Core version to 1.12.0

- build.gradle
> Update Mockito version to 5.11.0

- build.gradle
> Update Jackson-databind version to 2.15.4

- build.gradle
> Update Lombok version to 1.18.30

- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
> Fix showing invisible element in Diagnostics logs

- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/loader/CentralConfigurationClient.java
> Fix showing "No Internet connection" message

- app/src/main/res/layout/signature_update.xml
> Fix scrolling in signing view with big text size

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
> Fix showing rooted screen

- app/src/main/java/ee/ria/DigiDoc/android/main/settings/proxy/SettingsProxyDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/SettingsFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/SettingsSigningView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/TsaUrlPreferenceDialogFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/UUIDPreference.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/UUIDPreferenceDialogFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/siva/SettingsSivaDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/TextUtil.java
- app/src/main/res/layout/main_diagnostics.xml
- app/src/main/res/layout/main_settings_proxy_dialog_layout.xml
- app/src/main/res/layout/main_settings_rights.xml
- app/src/main/res/layout/main_settings_signing.xml
> Fix TalkBack focus on switches

- app/src/main/java/ee/ria/DigiDoc/android/main/diagnostics/DiagnosticsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/rights/SettingsRightsView.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/SettingsSigningView.java
> Fix accessibility feedback when toggle value is changed

- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/UUIDPreference.java
- app/src/main/res/layout/main_about_screen.xml
- app/src/main/res/layout/main_accessibility.xml
- app/src/main/res/layout/main_diagnostics.xml
- app/src/main/res/layout/main_home_toolbar.xml
- app/src/main/res/layout/signature_home.xml
- app/src/main/res/layout/signature_update_list_item_name.xml
- app/src/main/res/layout/signature_update_list_item_subhead.xml
> Fix accessibility moving with keyboard

- app/src/main/java/ee/ria/DigiDoc/android/utils/RootUtil.java
> Detect root on device

- gradle.properties
> Updated app version to 2.7.0

- .github/workflows/build.yml
> Fix updating libdigidocpp in Github Actions

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Result.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
> Fix showing crypto container download button

- id-card-lib/src/main/java/ee/ria/DigiDoc/idcard/NFC.java
MOPPAND-1345
Removed irrelevant fixme-s, added NFCException and result code
Signed-off-by: Lauris Kaplinski <lauris.kaplinski@raulwalter.com>
> Removed fixmes

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/container/ContainerUtil.java
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Show message when files already exist in container

- .github/workflows/build.yml
- .github/workflows/codeql.yml
- .github/workflows/coverity_scan.yml
- app/build.gradle
- build.gradle
> Fix Github Actions

- app/src/main/java/ee/ria/DigiDoc/android/model/smartid/SmartIdStatusMessages.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/detail/SignatureDetailView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- common-lib/src/main/java/ee/ria/DigiDoc/common/UserAgentUtil.java
- smart-id-lib/src/main/AndroidManifest.xml
- smart-id-lib/src/main/java/ee/ria/DigiDoc/smartid/service/SmartSignService.java
> Fix Android 14 Smart-ID notification handling

- gradle.properties
> Update version code

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/mobileid/MobileIdView.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/smartid/SmartIdView.java
> Fix textboxes accessibility

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateView.java
> Fix opening files from ASICS containers

- gradle.properties
> Update version code to 52

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/nfc/NFCOnSubscribe.java
- common-lib/src/main/res/values-et/strings.xml
- common-lib/src/main/res/values-ru/strings.xml
- common-lib/src/main/res/values/strings.xml
- id-card-lib/src/main/java/ee/ria/DigiDoc/idcard/NFC.java
> Add better message when NFC CAN number is wrong

- app/src/main/java/ee/ria/DigiDoc/android/utils/TextUtil.java
- app/src/main/res/layout/signature_update_nfc.xml
> Fix signing methods design

- build.gradle
- configuration-lib/build.gradle
- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/task/FetchAndPackageDefaultConfigurationTask.java
- gradle.properties
- gradle/wrapper/gradle-wrapper.properties
> Update Android Gradle version to 8.8.0

- build.gradle
> Update Crashlytics Gradle version to 3.0.2

- build.gradle
> Update AndroidX Annotation version to 1.9.1

- build.gradle
> Update Android Material version to 1.12.0

- build.gradle
> Update Guava version to 33.4.0

- build.gradle
> Update Okio version to 3.10.2

- build.gradle
> Update Commons Text version to 1.13.0

- build.gradle
> Update RxJava version to 3.1.10

- build.gradle
> Update Firebase Crashlytics version to 33.7.0

- build.gradle
> Update Truth version to 1.4.4

- app/src/main/java/ee/ria/DigiDoc/android/Activity.java
- app/src/main/res/values-v35/themes.xml
- app/src/main/res/values/themes.xml
- build.gradle
> Update Target SDK version to 35

- build.gradle
> Update AndroidX Test Orchestrator version to 1.5.1

- build.gradle
> Update Google Services version to 4.4.2

- build.gradle
> Update AndroidX AppCompat version to 1.7.0

- build.gradle
> Update AndroidX Lifecycle version to 2.8.7

- build.gradle
> Update Commons IO version to 2.18.0

- build.gradle
> Update Gson version to 2.11.0

- build.gradle
> Update Mockito version to 5.15.2

- build.gradle
> Update AndroidX Test version to 1.2.1

- build.gradle
> Update AndroidX Test Rules version to 1.6.1

- build.gradle
> Update AndroidX Test Espresso version to 3.6.1

- build.gradle
> Update jackson-databind version to 2.18.2

- build.gradle
> Update Lombok version to 1.18.36

- app/src/main/java/ee/ria/DigiDoc/android/ApplicationApp.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/proxy/SettingsProxyDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/model/idcard/IdCardService.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureAddSource.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/nfc/NFCOnSubscribe.java
- common-lib/src/main/java/ee/ria/DigiDoc/common/ContainerWrapper.java
- common-lib/src/main/java/ee/ria/DigiDoc/common/UserAgentUtil.java
- configuration-lib/src/androidTest/java/ee/ria/DigiDoc/configuration/ConfigurationManagerTest.java
- configuration-lib/src/main/java/ee/ria/DigiDoc/configuration/ConfigurationManagerService.java
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignedContainer.java
**MOPPAND-1504**
- Set Devices in User-Agent only for ID-Card signing.
- Some cleanup and warnings fixes.
Signed-off-by: Boriss Melikjan <boriss.melikjan@nortal.com>
> Set Devices in User-Agent only for ID-Card signing.

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
> Fix opening documents in signed PDFs

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateAdapter.java
- build.gradle
> Update AndroidX Core version to 1.15.0

- build.gradle
> Update LDAP SDK version to 7.0.2

- build.gradle
> Update SLF4j version to 2.0.16

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateAdapter.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateErrorDialog.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/exception/PINException.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/nfc/NFCOnSubscribe.java
> Fix wrong PIN2 message with NFC

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
> FIx ASICS signature view

- app/src/main/java/ee/ria/DigiDoc/android/utils/widget/NotificationDialog.java
- app/src/main/res/values-et/strings.xml
- app/src/main/res/values-ru/strings.xml
- app/src/main/res/values/strings.xml
> Update NFC Read more button and links

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/create/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/list/Intent.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/Processor.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/container/ContainerUtil.java
> Improve opening files with symbols

- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureUpdateErrorDialog.java
> Fix clickable Read More button

- app/src/main/java/ee/ria/DigiDoc/android/crypto/create/CryptoCreateScreen.java
- app/src/main/java/ee/ria/DigiDoc/android/main/settings/signing/UUIDPreferenceDialogFragment.java
- app/src/main/java/ee/ria/DigiDoc/android/utils/container/NameUpdateView.java
> Fix TalkBack cursor positions

- gradle.properties
> Update version code to 54

- gradle.properties
> Update version code to 63

- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignedContainer.java
> Improve dereferencing variable

- app/src/main/java/ee/ria/DigiDoc/android/model/idcard/IdCardService.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/SignatureAddSource.java
- app/src/main/java/ee/ria/DigiDoc/android/signature/update/nfc/NFCOnSubscribe.java
- common-lib/src/main/java/ee/ria/DigiDoc/common/UserAgentUtil.java
- sign-lib/src/main/java/ee/ria/DigiDoc/sign/SignedContainer.java
MOPPAND-1556
Set NFC true in User-Agent for NFC signing.
Signed-off-by: Boriss Melikjan <boriss.melikjan@nortal.com>
> Set NFC true in User-Agent for NFC signing.
